// angular/demo/src/app/samples/floatingUI/floatingUI.route.ts
import {AgnosUIAngularModule, createFloatingUI, floatingUI, toAngularSignal} from '@agnos-ui/angular';
import {ChangeDetectionStrategy, Component} from '@angular/core';

@Component({
	standalone: true,
	imports: [AgnosUIAngularModule],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `<div class="position-relative overflow-auto border border-primary-subtle floatingui-demo">
		<button [auUse]="floatingUI.directives.referenceDirective" type="button" class="btn btn-primary" (click)="displayPopover = !displayPopover">
			Toggle popover
		</button>
		@if (displayPopover) {
			<div
				[auUse]="floatingUI.directives.floatingDirective"
				[attr.data-popper-placement]="floatingUIState().placement"
				class="popover bs-popover-auto fade position-absolute"
				[class.show]="!floatingUIState().middlewareData?.hide?.referenceHidden"
				role="tooltip"
			>
				<div class="popover-arrow position-absolute" [auUse]="floatingUI.directives.arrowDirective"></div>
				<div class="popover-body">This is a sample popover</div>
			</div>
		}
	</div>`,

	styles: `
		div.floatingui-demo {
			width: 500px;
			height: 200px;
		}
		button {
			margin: 500px;
		}
		button,
		.popover {
			width: max-content;
		}
	`,
})
export default class FloatingUIComponent {
	displayPopover = true;

	floatingUI = createFloatingUI({
		props: {
			arrowOptions: {
				padding: 6,
			},
			computePositionOptions: {
				middleware: [
					floatingUI.offset(10),
					floatingUI.autoPlacement(),
					floatingUI.shift({
						padding: 5,
					}),
					floatingUI.hide(),
				],
			},
		},
	});
	floatingUIState = toAngularSignal(this.floatingUI.state$);
}

// react/demo/app/samples/floatingUI/FloatingUI.route.tsx
import {createFloatingUI, floatingUI, useDirective, useObservable} from '@agnos-ui/react';
import {useMemo, useState} from 'react';

const FloatingUI = () => {
	const [displayPopover, setDisplayPopover] = useState(true);
	const floatingUIInstance = useMemo(
		() =>
			createFloatingUI({
				props: {
					arrowOptions: {
						padding: 6,
					},
					computePositionOptions: {
						middleware: [
							floatingUI.offset(10),
							floatingUI.autoPlacement(),
							floatingUI.shift({
								padding: 5,
							}),
							floatingUI.hide(),
						],
					},
				},
			}),
		[],
	);
	const floatingUIState = useObservable(floatingUIInstance.state$);
	const refReference = useDirective(floatingUIInstance.directives.referenceDirective);
	const refFloating = useDirective(floatingUIInstance.directives.floatingDirective);
	const refArrow = useDirective(floatingUIInstance.directives.arrowDirective);

	return (
		<div className="position-relative overflow-auto border border-primary-subtle floatingui-demo" style={{width: '500px', height: '200px'}}>
			<button
				ref={refReference}
				type="button"
				className="btn btn-primary"
				onClick={() => setDisplayPopover(!displayPopover)}
				style={{margin: '500px', width: 'max-content'}}
			>
				Toggle popover
			</button>
			{displayPopover ? (
				<div
					ref={refFloating}
					data-popper-placement={floatingUIState.placement}
					className={`popover bs-popover-auto fade position-absolute ${!floatingUIState.middlewareData?.hide?.referenceHidden ? 'show' : ''}`}
					style={{width: 'max-content'}}
					role="tooltip"
				>
					<div className="popover-arrow position-absolute" ref={refArrow}></div>
					<div className="popover-body">This is a sample popover</div>
				</div>
			) : null}
		</div>
	);
};
export default FloatingUI;
